### ISSUE TITLE
More documents are appreciating

### ISSUE THREAD

**Issue by MRYingLEE** [hkroger/cqlfs#1]
More documents are appreciating.

It's an interesting idea to build a Cassandra based file system. And your work is a good starting point for anyone who has the same idea, such as me.

But your documents are weak. Can you share more your experience and ideas?

For example, you mentioned the cqlfs was very slow. What's the reasons you think? It is because of Cassandra itself, File Block Read/Write, File Meta Read/Write or something else?

Thank you in advance,
Ying

**Comment by hkroger** [comment]
One of the reasons why it is so slow is the lack of caching/buffering on the driver side. If we use for example block size of 4096 and for some reason the FS is writing in chunks of 512, then we have to read out the block, update the block and write back the block 8 times before we are done and when all this is synchronous, it gets very slow.

So to solve this, it would be helpful to add some caching/buffering and make the FS driver more asynchronous when it writes to Cassandra.

If there is some level of caching, then there should be as well a method for invalidating those caches between cqlfs instances. Some sort of publish/subscribe mechanism is needed and Cassandra itself doesn't provide anything for so some centralized but distributed pub/sub merchanism would be needed.

**Comment by MRYingLEE** [comment]
Thank you very much.

Ying
