### ISSUE TITLE
What's your pre-requirement on build?

### ISSUE THREAD

**Issue by MRYingLEE** [hkroger/cqlfs#2]
Following your instruction, I used cmake and make to build CqlFS. I replace " #include <osxfuse/fuse/fuse.h>" with "#include <fuse.h>" to use the local fuse.h in the OS (CentOS 7).

But I met a few compiling errors. I made some adjustments, such as to include more files, but there were still some compiling errors left. 

For example, "non-trival designated initializers not supported" related to:
    struct fuse_operations cqlfs_filesystem_operations {...}
in cqlfs.cpp (line:604).

Just wonder what's your pre-requirements on build.  Do you support OSX only?

BTW, I am using cmake 3.5.2. 

Can you clarify?

Thank you in advance,

Ying

**Comment by hkroger** [comment]
Are you building on something else than OSX? Probably it's pretty straightforward to make it compile on any unix platform but I just do my development on OSX so I haven't tested anything else.

**Comment by MRYingLEE** [comment]
I am working on CentOS7.

Thank you anyway,

Ying
